### ISSUE TITLE
CuBLAS

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#10]
Now that the float32 bugs appear to have been resolved, time to start porting CuBLAS

**Comment by chewxy** [comment]
CuBLAS may have to take a step back. Looking at integrating CuDNN instead

**Comment by Grillz** [comment]
Hey @chewxy I'm really interested in this project but my one blocker is lack of CUDNN support. Have you investigated/started this at all? Thanks

**Comment by chewxy** [comment]
the chad branch will fully support CuDNN. Work is being done right now to support it. See also: https://github.com/chewxy/cu

**Comment by Grillz** [comment]
Awesome news, look forward to using it 👍
