### ISSUE TITLE
Guidelines on use of Borrow and Return

### ISSUE THREAD

**Issue by kabaka0** [chewxy/gorgonia#100]
For consistency, it would be good to have guidelines on when to use Borrow in contributed code. It would be great if Borrow/Return could be the default for allocation (including new types going forward)- it would make contributing to the code easier, as well as make it easier to manage performance. You could probably do this without too much of a performance hit, although the Borrow/Return functions would need to become a bit more complex to make sure that returns only correspond to borrowed objects. Thoughts on this?

**Comment by chewxy** [comment]
This issue was moved to gorgonia/tensor#12
