### ISSUE TITLE
Is there any detailed document?

### ISSUE THREAD

**Issue by lvjiangzhao** [chewxy/gorgonia#101]
Is there any detailed document such as user guides for someone to use this library more easily ? I have only found some infomation in Readme.

**Comment by damienstanton** [comment]
@lvjiangzhao There is a static website coming to help with this. See #80

**Comment by lvjiangzhao** [comment]
@damienstanton Hope this site available ASAP since I am quite puzzled with some concepts and usages.

**Comment by chewxy** [comment]
In the meantime, you can send me an email. It's chewxy[at]gmail.com .

**Comment by lvjiangzhao** [comment]
@chewxy Thx. I'll email you if there is something hard to understand.

**Comment by chewxy** [comment]
Cool
