### ISSUE TITLE
CUDA warning

### ISSUE THREAD

**Issue by grafael** [chewxy/gorgonia#102]
Have I to explicit change the source code to use CUDA instructions? Like in the CUDA example _T.UseCudaFor("tanh")_ ?

I'm asking that because I was compiling all my code with tag='cuda' , the compiler says "Using CUDA build"  and later on I realize that my GPU was not being used at all.

Maybe we could warn the user that there are no CUDA instructions to be built.

**Comment by chewxy** [comment]
Yes. But in the upcoming PR (#93)  , this need will be obiviated. For now you can just use `T.UseCudaFor()`  if you want all ops to use CUDA (though it's not advised because it'll generally be slower due to cgo calls).

**Comment by grafael** [comment]
Thanks @chewxy looking forward to see the capabilities of CUDAMachine

**Comment by chewxy** [comment]
No problem. Glad I could help. Any time you need help you can just email me (at gmail.com)
