### ISSUE TITLE
Cannot run examples in Go 1.8

### ISSUE THREAD

**Issue by linkerlin** [chewxy/gorgonia#108]
import error, missing definitions.
run auto encoder:
go run main.go 
# command-line-arguments
./main.go:46: undefined: Label
./main.go:47: undefined: RawImage
./main.go:62: undefined: readLabelFile
./main.go:62: undefined: open
./main.go:66: undefined: readImageFile
./main.go:66: undefined: open
./main.go:70: undefined: prepareX
./main.go:71: undefined: prepareY
./main.go:154: undefined: NewStackedDA
./main.go:202: undefined: visualizeRow
./main.go:202: too many errors

**Comment by chewxy** [comment]
try `go run *.go`

The program is split into multiple files

**Comment by chewxy** [comment]
Note you will also need the files from Yann LeCun's website for the MNIST data (I'm on my way out right now so if you haven't found it by the time I get back in 5 hrs I'll find it for you)

**Comment by chewxy** [comment]
Also the stackedDA example is quite stale. Probably hasn't kept up with all the changes. It'll be fixed in the upcoming merge

**Comment by linkerlin** [comment]
go run *.go
is ok.
Go 1.8's import is changed. It will not search go-files in the same folder.
Move all other-files to other packages then main-package may solve the problem.

**Comment by chewxy** [comment]
Oh I've always run `go run *.go`. I didn't know you could run `go run
main.go`



*Xuanyi Chew*
*@chewxy on Twitter*
*Read:* my blog <http://blog.chewxy.com>
*+61403928398*
