### ISSUE TITLE
What about Deep Forest: Towards An Alternative to Deep Neural Networks?

### ISSUE THREAD

**Issue by linkerlin** [chewxy/gorgonia#109]
[Deep Forest: Towards An Alternative to Deep Neural Networks](https://arxiv.org/abs/1702.08835)

**Comment by chewxy** [comment]
Cool paper. I can't implement this right now - not for at least two more months. Feel free to implement it tho

**Comment by unixpickle** [comment]
The results in that paper were actually fairly far from state of the art, even on easy problems like MNIST. Slaving over an implementation is probably not worth it.
