### ISSUE TITLE
Any plan to support ARIMA?

### ISSUE THREAD

**Issue by rafw** [chewxy/gorgonia#118]
ARIMA could be used for forecast.

**Comment by chewxy** [comment]
Funny you mention that. My new job has a lot of ARIMA related works, so yes. I'll be eventually building out ARIMA support.

Why don't you help by making pull requests? A very good place to start is the [Hyndsights blog](https://robjhyndman.com/hyndsight/) - Rob has amongst the more userfriendly forecasting tools (though sadly in R)
