### ISSUE TITLE
Awesome stuff

### ISSUE THREAD

**Issue by joeblew99** [chewxy/gorgonia#119]
Huge thank you chewxy for doing this on github. 
I have lots of ML python friends and worked with 25 on a project.
All python and spark. Was such a ball of fluff and sticky tape.
Looking forward to using and extending this repo.

How about a roadmap ? Me and others can help. 
One thing we found needed was good tools for holding data that is versiined. This often holds your "ground truth" data that you use to train with. 
It's normally huge and you want to keep it around because you often need to blow away your learnt dataset and retrain as your ground truth data improves.

Or you can incorporate Providence into your learnt data. This is just a link data to the ground truth data. This way when you improve your ground truth data you can which parts of your learnt data can be deleted and rerun the learning on just the new ground truth data.

Also about scaling this thing out.
Pachyderm are ok.
I am getting pretty hot on kappa architectures using actors. Makes things easy to scale up OR out.

https://github.com/AsynkronIT/protoactor-go

Scale UP means increases the speed of 1 result, and requires data parallelism. Actors can do that for you.
Scale OUT means increasing the throughput. Each calculation takes the same time, but you can handle many of them.

**Comment by chewxy** [comment]
I've been looking for a git for models... played with Pachyderm, Dat and ModelDB, found all to be okay but not as userfriendly as git (yes I said it, git is userfriendly). ModelDB I think makes everything doubly complex by giving it a webbased UI. Ugh.

Currently I'm stuck using gitannex, but that sucks balls for versioning machine learning data. I'm inching very slowly towards Pachyderm (thanks to the phenomenal efforts of @dwhitena) 

As for roadmap, I'll get back to you - I've been taken ill by some dodgy thai food earlier in the evening and it's a rather long explanation

**Comment by joeblew99** [comment]
I went done the same road.

Yeah gitannex is kind of sloppy hacked on thing  I used it too.

Noms looks good to me. Check it out...
It's ready too.
https://github.com/attic-labs/noms/tree/master/samples/go

Is 100% golang so model sharing is possible too, which can be leveraged in various ways.

Sorry about you feeling a bit sick. Take it easy and recuperate - the sun will come up tomorrow :)

**Comment by dwhitena** [comment]
Hi @chewxy and @joeblew99!  I'm definitely happy to help on the Pachyderm front any time.  A couple of good examples that you could work off are: http://docs.pachyderm.io/en/latest/examples/readme.html#machine-learning

Here is a little more info on ML workflows in Pachyderm: http://docs.pachyderm.io/en/latest/cookbook/ml.html

And here is a local install that is useful for testing/dev: http://docs.pachyderm.io/en/latest/getting_started/local_installation.html

Pachyderm definitely has data versioning for individual training sets and models.  However, I think the real power comes from the combination for data pipelining and versioning.  By combining these elements you are able to connect certain results with certain versions of models and corresponding versions of training sets, for example, without manually tracking that sort of thing.

**Comment by joeblew99** [comment]
@dwhitena thanks for chiming in. I looked at Pachy a year ago.

Can i ask a few questions ?

1. I dont need to FFI betwen languages or shell / bash. I prefer to be 100% inside golang with everything. Is there an example showing this yet ?

2. Can i run on mobile ? I run allot of learning on small devices at the edge of the network. Its the only way to overcome the bandwidth issue. SO i run on rapsberry Pi devices and mobiles.

As you can see from above its more like i want a library. I still need a server too.

**Comment by chewxy** [comment]
Stale for now
