### ISSUE TITLE
FromScalar makes no sense with mask

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#132]
```go
// FromScalar is a construction option for representing a scalar value as a Tensor
func FromScalar(x interface{}, argMask ...[]bool) ConsOpt {
	var mask []bool
	if len(argMask) > 0 {
		mask = argMask[0]
	}

	f := func(t Tensor) {
		switch tt := t.(type) {
		case *Dense:
			xt := reflect.TypeOf(x)
			xv := reflect.New(xt)
			xvi := reflect.Indirect(xv)
			xvi.Set(reflect.ValueOf(x))
			ptr := xv.Pointer()
			uptr := unsafe.Pointer(ptr)

			tt.ptr = uptr
			tt.l = 1
			tt.c = 1
			tt.v = x
			tt.t = Dtype{xt}
			tt.mask = mask
			tt.shape = 

		default:
			panic("Unsupported Tensor Type")
		}
	}
	return f
}
```

A scalar value should not be masked. Is there a reason why a scalar value is maskable? @kabaka0 

There are various instances where `retVal = New(FromScalar(argmaxI(t.Ints(), t.mask)))` or something similar is called, but I cannot for rhyme or reason figure out why.

**Comment by kabaka0** [comment]
My logic was that there could be cases in which a scalar is masked, such as, say, a reduction operation from a masked array (say all elements invalid) that results in an invalid scalar.  I opted as a result to include the option of creating a scalar with a mask, given that it is not  forbidden. I believe that numpy also supports masked 'scalars'.

**Comment by kabaka0** [comment]
Also in the case you quote, `retVal = New(FromScalar(argmaxI(t.Ints(), t.mask)))`, the return value is a regular (unmasked) scalar, the mask is only used in `argmask`

**Comment by chewxy** [comment]
OK. Thanks. Very helpful. Can you craft a documentation for this? Thanks

**Comment by kabaka0** [comment]
Sure, I will do!

**Comment by chewxy** [comment]
(btw, just send a PR, I'll merge your documentation before #127

**Comment by chewxy** [comment]
This issue was moved to gorgonia/tensor#7
