### ISSUE TITLE
WithShape should accept type Shape or []int input

### ISSUE THREAD

**Issue by siquus** [chewxy/gorgonia#134]
I am doing something like this:
```
func DatasetTrain(dtrain, dlabel tensor.Tensor) error {
	dtrain_shape := dtrain.Shape()
        g := G.NewGraph()
	input := G.NewTensor(g, tensor.Int8, G.WithName("input"), G.WithShape(dtrain_shape[0], dtrain_shape[1], dtrain_shape[2]))
```
and it would feel more natural if I could simply use 
`G.WithShape(dtrain_shape)`
or something along the lines.

**Comment by chewxy** [comment]
You can do this

`G.WithShape(dtrain_shape...)` 

:)

**Comment by siquus** [comment]
Works. Well that is embarrassing - in my defence: I spend all of my professional life in C ;-) 
Thanks!
