### ISSUE TITLE
Add tensordot (a.k.a Tensor Contraction, Tensor Multiply) to operations

### ISSUE THREAD

**Issue by siquus** [chewxy/gorgonia#167]
In machine learning, usually one can cast the input data into a standard shape as one e.g. does not care whether a 2d picture will be represented by a 1d vector inside the computational graph.

However, when doing other numerical computations, it is highly desirable to be able to contract tensors directly (as the function TensorMul shows ;-) ).

**Comment by chewxy** [comment]
I think this needs to be filed in github.com/gorgonia/tensor

**Comment by siquus** [comment]
Well, actually I did create a local branch to add this operation (all Op Interface Methods work on that branch) I am trying to figure out how to get this branch uploaded (and yes, I was looking at your contributions.md just now ;-) ).

Anyhow: I only changed one file in tensor/api_arith.go and a couple in gorgonia. So it's in both repositories.

**Comment by chewxy** [comment]
send a PR, I'll merge in. Add yourself to first section of CONTRIBUTORS.md (or I can add that for you)

Thank you so much for doing this

**Comment by siquus** [comment]
Done #168 .

**Comment by chewxy** [comment]
Left a few comments - would love your thoughts. Also there is a conflict. I'm going back to bed. Will merge this in first thing when I wake up again.

**Comment by chewxy** [comment]
merged #168
