### ISSUE TITLE
Slicing tensor

### ISSUE THREAD

**Issue by kubaroth** [chewxy/gorgonia#175]
A newbie question. What is an idiomatic way to slice the tensor? 
I've only seen rs struct being defined which implements Slice interface - but it seems be only available for inter usage.  Should I define my "range-slice" myself?
Thanks

**Comment by chewxy** [comment]
You got that right. You should define your own. I've been mulling an alternate package where there are Gorgonia Utilties

**Comment by kubaroth** [comment]
Ok, thanks. For people coming from other libraries (Numpy) would be nice to have a some sort of quick reference chart for common operation. Similar to this http://eigen.tuxfamily.org/dox/group__QuickRefPage.html
This may increase adoption - and save you time writing/maintaining another package :)

**Comment by chewxy** [comment]
https://www.cheatography.com/chewxy/cheat-sheets/data-science-in-go-a/

**Comment by kubaroth** [comment]
Very nice!
