### ISSUE TITLE
Support Batched BLAS/External (Cgo/CUDA/OpenCL) for *LispMachine

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#4]
`*LispMachine` should keep track of node dependencies and then perform batched BLAS calls. This would enable future use of CuBLAS ops

**Comment by chewxy** [comment]
This one will be updated. Batching should be handled by the VMs

**Comment by fivejjs** [comment]
This will be good stuff considering AMD speedup their product release.

**Comment by chewxy** [comment]
This is coming soon (well, the architecture anyway - see the current PR pending). The new architecture allows for the dynamic machines to use `BatchedBLAS` and `CUDA`. Also I have no ryzen machine to test on yet... so I am not sure how to play with that.

**Comment by chewxy** [comment]
This was fixed in 215b466d
