### ISSUE TITLE
Rework errors

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#46]
This task is broken into two parts:
- Wrap all errors in Gorgonia with the [errors](https://github.com/pkg/errors) package, with meaningful error messages.
- Remove all of the `runtime.Caller()` function from the basic errors.

**Comment by robjloranger** [comment]
i'd like to take a shot at this

**Comment by chewxy** [comment]
Added you to the list of collaborators. It's just so I can assign the issue. Please use a personal fork and send a pull request

**Comment by robjloranger** [comment]
Awesome, will do. Thanks 😃

**Comment by robjloranger** [comment]
I haven't had time to wrap my head around this. I'll keep looking back to it but if anyone else wants to take it on please do.

**Comment by chewxy** [comment]
Cool. thank you Rob

**Comment by NDari** [comment]
I have started work on this Issue. The WIP is in the PR above.

**Comment by chewxy** [comment]
Thank you. I'll add you to the list of assignees

**Comment by chewxy** [comment]
This should have been closed.
