### ISSUE TITLE
Readme example differentiation typo

### ISSUE THREAD

**Issue by HeinOldewage** [chewxy/gorgonia#50]
The code only prints the value if an error occurred. The ifs should test for err == nil.

    if xgrad, err := x.Grad(); err != nil {
        fmt.Printf("dz/dx: %v", xgrad)
    }

    if ygrad, err := y.Grad(); err != nil {
        fmt.Printf("dz/dy: %v", ygrad)
    }

**Comment by chewxy** [comment]
Right you are! Could you make a PR? I'm abroad atm, but can merge pull requests
