### ISSUE TITLE
Sigmoid for Tensors are slow

### ISSUE THREAD

**Issue by chewxy** [chewxy/gorgonia#64]
Mainly due to the fact that Tensor.Apply(sigmoidFn) is slow. There should be a way to optimize this for entire arrays

**Comment by chewxy** [comment]
The plan is to write SIMD versions of vecExp for both Float32 and Float64 tensors. Estimated start time, sometime next week

**Comment by kabaka0** [comment]
What is the status on this?

**Comment by chewxy** [comment]
Got sidetracked with the tensor package refactor. However, now application is fairly trivial. Will push the changes thru in a couple of days.

**Comment by chewxy** [comment]
More delays on this - CUDA support sidetracked me once again

**Comment by chewxy** [comment]
Solution to this for now is to us CUDA. Will close this for now.
