### ISSUE TITLE
Exposing TensorType struct members

### ISSUE THREAD

**Issue by kabaka0** [chewxy/gorgonia#75]
I am writing a custom operator, which needs to implement Type() as per the Op interface. The operator outputs is a tensor, hence the need for TensorType. Given that you chose to export neither fromTensorType(,)  nor newTensorType(,) and the members of TensorType (d and of) are private, is there a better way for me to do this, other than refactoring  gorgonia/type.go or copy-pasting TensorType (and it's methods) from gorgonia/type.go into my project?

**Comment by chewxy** [comment]
I could have sworn that it was exported. Either way, FTFY :)

**Comment by kabaka0** [comment]
That's great - unbelievably quick response, thank you! Really good job on this project by the way.

**Comment by chewxy** [comment]
Tests passed. Merged into master :)

p/s: Tensors are gonna change over the coming days. I may provide a fix tool, but chances are I may not

**Comment by kabaka0** [comment]
Appreciate the heads up. I have only just started integrating gorgonia into my project and so it will personally not be a problem refactoring where needed.
