### ISSUE TITLE
Creating node for custom operator

### ISSUE THREAD

**Issue by kabaka0** [chewxy/gorgonia#77]
This is about creating a node for a custom operator. What do you think about exposing newUniqueNode, withType(), withOp(), withChildren() and withGraph()? It would make it a lot easier to create new nodes without having to copy-paste code you have already written, into new functions.

**Comment by chewxy** [comment]
jaysus. You have caught something I hadn't noticed. You may have noticed some `nodeconsopt` were exported and some were not. They're meant to be all exported. Gimme a few hrs to fix this - Chinese New Year celebrations to contend with

**Comment by chewxy** [comment]
Fixed :)

**Comment by kabaka0** [comment]
Thanks again, really appreciate the fast fixes.

**Comment by chewxy** [comment]
Hey @kabaka0 I've updated the Tensor library now. It's all unified. These are the major fixes needed:

* No more `gorgonia.Dtype` - use `tensor.Dtype`
* No more `tensor/types` package
* `AsScalar` has been renamed to `FromScalar`
* No more tf64/tf32/... Below are the changes to the patterns you may come across (sorry I didn't have time to write a fixer program)

 ```go 
 x := tf64.NewTensor(tf64.WithBacking(xBack), tf64.WithShape(2,3))
``` 
becomes:  
```go 
 x := tensor.New(tensor.WithBacking(xBack), tensor.WithShape(2,3))
```
--- 
 ```go 
 x := tf64.NewTensor(tf64.WithShape(2,3))
 ``` 
becomes:
``` go
 x := tensor.New(tensor.Of(tensor.Float64), tensor.WithShape(2,3))
```
---
```go
x := tensor.New(types.Float64, tensor.WithShape(2,3), tensor.WithBacking(xBack))
```
becomes:
```go
x := tensor.New(tensor.WithShape(2,3), tensor.WithBacking(xBack))
```
---
```go
x := tensor.New(types.Float64, tensor.WithShape(2,3))
```
becomes:
```go
x := tensor.New(tensor.Of(tensor.Float64), tensor.WithShape(2,3))
```
---
```go
x := tf64.NewTensor(AsScalar(3.14))
```
becomes:
```go
x := tensor.New(FromScalar(3.14))
```

**Comment by kabaka0** [comment]
I feel that this counts as a significant step forward - the code is a lot clearer now. Great job. Do you plan any more major refactoring? If not, I'd be happy to start actively contributing where needed.

**Comment by chewxy** [comment]
Not for the tensor package. I might move a few things into the `Tensor` interface (I discovered this made more sense when I wrote the documentation...) but yeah, the `tensor` package is frozen (for the most part) for now. Only improvements to be made are performance related.
